drop table if exists users, films, likes, genres, mpa, user_friends, genre_films;

create table if not exists users (
  id integer generated by default as identity not null primary key,
  login varchar(100) not null unique,
  name varchar(100),
  email varchar(100) not null unique,
  birthday date
);

create table if not exists  films (
  id integer generated by default as identity not null primary key,
  name varchar(100) not null,
  description varchar(200),
  release_date date,
  duration integer not null,
  mpa_id integer
);

create table if not exists  likes (
  user_id integer,
  film_id integer,
  primary key (user_id, film_id)
);

create table if not exists  genres (
  id integer generated by default as identity not null primary key,
  name varchar(100) not null
);

create table if not exists  mpa (
  id integer generated by default as identity not null primary key,
  name varchar(10)
);

create table if not exists  user_friends (
  user_id integer,
  friends_id integer,
  primary key (user_id, friends_id)
);

create table if not exists  genre_films (
  genre_id integer,
  film_id integer,
  primary key (genre_id, film_id)
);

alter table likes add foreign key (film_id) references films (id);

alter table likes add foreign key (user_id) references users (id);

alter table films add foreign key (mpa_id) references mpa (id);

alter table genre_films add foreign key (film_id) references films (id);

alter table genre_films add foreign key (genre_id) references genres (id);

alter table user_friends add foreign key (user_id) references users (id);

alter table user_friends add foreign key (friends_id) references users (id);

